defmodule Reify.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:todos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :completed, :boolean, null: false, default: false
      add :title, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    # Case-insensitive unique index using lower()
    execute "CREATE UNIQUE INDEX todos_unique_title_index ON todos (lower(title))"
  end

  def down do
    execute "DROP INDEX IF EXISTS todos_unique_title_index"

    drop table(:todos)
  end
end
