/**
 * Todo Events - re-exports from consolidated generated file.
 *
 * Source of truth: lib/reify/demos/todos/events.ex
 * Generated by: mix reify.gen.events_ts
 */

export {
  TodoClientEvents,
  TodoServerEvents,
  type TodoClientEvent,
  type TodoClientEventPayloads,
  type TodoServerEvent,
} from "../../events.generated";

// Re-export payload types from ash_rpc
export type {
  CreateTodoInput,
  ToggleTodoInput,
  UpdateTitleInput,
  DeleteTodoInput,
} from "../../ash_rpc";
